FROM openjdk:17-slim

WORKDIR /app

ARG DISCORD_BOT_TOKEN
ARG AMAZON_AWS_REGION
ARG AMAZON_AWS_ACCESSKEY
ARG AMAZON_AWS_SECRETKEY
ARG TWITCH_API_CLIENT_ID
ARG TWITCH_API_CLIENT_SECRET
ARG YOUTUBE_API_KEY

ENV DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN
ENV AMAZON_AWS_REGION=$AMAZON_AWS_REGION
ENV AMAZON_AWS_ACCESSKEY=$AMAZON_AWS_ACCESSKEY
ENV AMAZON_AWS_SECRETKEY=$AMAZON_AWS_SECRETKEY
ENV TWITCH_API_CLIENT_ID=$TWITCH_API_CLIENT_ID
ENV TWITCH_API_CLIENT_SECRET=$TWITCH_API_CLIENT_SECRET
ENV YOUTUBE_API_KEY=$YOUTUBE_API_KEY

COPY target/*.jar /app/app.jar

ENTRYPOINT ["java","-jar","app.jar"]