package org.yolok.he1pME.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.xspec.S;
import lombok.*;

import java.awt.*;

@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "CallAction")
public class CallAction {

    @DynamoDBHashKey
    private String action;

    @DynamoDBAttribute(attributeName = "guild_id")
    private String guildId;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private String image;

    @DynamoDBAttribute
    private String message;

    @DynamoDBAttribute
    private String name;
}
