name: Run Tests

on:
  push:
    branches:
      - develop

jobs:
  Test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up Java
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 17
          distribution: oracle

      - name: Set Up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2

      - name: Run Unit Tests
        run: mvn -B test
